### ISSUE TITLE
Crash when incoming message has nil field "Sender"

### ISSUE THREAD

**Issue by alex-godwin** [perlin-network/noise#160]
I've been having random crashes with a peer (sometimes connected to other peers, and sometimes on it's own) with the error:
```
2018/09/19 16:45:50
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa3815d]

goroutine 49 [running]:
github.com/gladiusio/gladius-node/vendor/github.com/perlin-network/noise/network.(*Network).Accept.func2(0xc4203aba60, 0xc420312d00, 0xc42006c380, 0xc42000f220, 0xc4203ad6b0, 0xc4203ad690, 0xc4203df890)
        /ext-go/1/src/github.com/gladiusio/gladius-node/vendor/github.com/perlin-network/noise/network/network.go:402 +0xed
created by github.com/gladiusio/gladius-node/vendor/github.com/perlin-network/noise/network.(*Network).Accept
        /ext-go/1/src/github.com/gladiusio/gladius-node/vendor/github.com/perlin-network/noise/network/network.go:375 +0x1d4
```
The random nature of this, and the fact it happens when there are no peers connected makes me think it's this section of our code:
```golang
func (state *StatePlugin) Startup(net *network.Network) {
	// TODO: Find out why this crashes the network on ocassion
	 go func() {
		time.Sleep(60 * time.Second)
	 	net.BroadcastRandomly(&messages.SyncRequest{}, 1)
	 }()
}
```
It looks like this if statement is the problem at `network.go:402`, dereferencing `msg.Sender` causes a panic. 
```golang
// Peer sent message with a completely different ID. Disconnect.
if !client.ID.Equals(peer.ID(*msg.Sender)) {
	glog.Errorf("message signed by peer %s but client is %s", peer.ID(*msg.Sender), client.ID.Address)
	return
}
```
I also get an error about the peer should not dial itself even if I haven't explicitly called `p.net.Bootstrap(addressList...)` so I believe that the above code is broadcasting before the network has been bootstrapped, and that the `BroadcastRandomly` method seems to be able to dial itself. This is running on a VPS and listening on it's public IP with the code:

```golang
// Use KCP instead of TCP, and config bind address and bind port
builder.SetAddress(network.FormatAddress(
	"kcp",
	viper.GetString("P2P.BindAddress"),
	uint16(viper.GetInt("P2P.BindPort")))

// This is our network state object
s := state.New()
s.RegisterNodeSingleFields("ip_address", "content_port", "heartbeat")
s.RegisterNodeListFields("disk_content")

s.RegisterPoolListFields("required_content")

// Register peer discovery plugin.
// TODO: Setup an authorized DHT plugin
builder.AddPlugin(new(discovery.Plugin))

// Add the exponential backoff plugin
builder.AddPlugin(new(backoff.Plugin))

// Create our state sync plugin
statePlugin := new(StatePlugin)
statePlugin.peerState = s
builder.AddPlugin(statePlugin)

net, err := builder.Build()
if err != nil {
	log.Fatal(err)
	return nil
}

go net.Listen()
```
I haven't tested with TCP instead of KCP though.

**Comment by alex-godwin** [comment]
So doing more testing, it looks like this is a related issue and can be repeated if you:
1) Connect a peer to a remote with the bootstrap method 
2) Kill the local peer
3) Restart (and generate a new random keypair) and reconnect to the same remote with the bootstrap method
4) The remote peer panics

```
2018/09/20 21:09:40
panic: close of closed channel

goroutine 143 [running]:
github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network.(*Network).Accept.func2.1()
	/home/alex/go/src/github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network/network.go:393 +0x185
sync.(*Once).Do(0xc4200c28e0, 0xc4203c3f68)
	/usr/lib/go-1.10/src/sync/once.go:44 +0xbe
github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network.(*Network).Accept.func2(0xc4200c28e0, 0xc42030cb60, 0xc420066d40, 0xc42000e060, 0xc42001f660, 0xc42001f650, 0xc4201048a0)
	/home/alex/go/src/github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network/network.go:377 +0xca
created by github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network.(*Network).Accept
	/home/alex/go/src/github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network/network.go:375 +0x1d4
```

**Comment by jack0** [comment]
Thanks for reporting this Alex. I'll look into it and fix the issue.

**Comment by alex-godwin** [comment]
Great, thanks so much. Let me know if I can provide more info about the setup, or if you have any problems replicating the issue.

**Comment by iwasaki-kenta** [comment]
The issue is guaranteed to no longer exist with Noise v2.0. Peer IDs are now cached after a handshake has been established, leaving there to be no need to continuously send the `Sender` field on each message.
