### ISSUE TITLE
Remotely crash a peer by binding to 0.0.0.0

### ISSUE THREAD

**Issue by alex-godwin** [perlin-network/noise#161]
If the local peer binds to `0.0.0.0` with the code

```golang
builder.SetAddress(network.FormatAddress(
	"kcp",
	"0.0.0.0",
	7946))
```

and a message is sent to the remote (in my case the initial state sync), the remote peer will try to dial itself and panic with the error:

```
E1001 14:12:43.652615    6010 network.go:397] network: peer should not dial itself
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa6fecd]

goroutine 48 [running]:
github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network.(*Network).Accept.func2(0xc0003ba840, 0xc0002d1ee0, 0xc000350c80, 0xc00000e170, 0xc0003b87f0, 0xc0003b87d0, 0xc0003b51a0)
        /home/alex/go/src/github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network/network.go:402 +0xed
created by github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network.(*Network).Accept
        /home/alex/go/src/github.com/gladiusio/gladius-controld/vendor/github.com/perlin-network/noise/network/network.go:375 +0x1cf
```

**Comment by alex-godwin** [comment]
#162 Put in a PR to address this

**Comment by alex-godwin** [comment]
Closing this because fixed in master
